### PR TITLE
browserify-i18n on npm is already taken -> browserifyi18n

### PR DESCRIPTION
**Pull request by kahnvex**

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by kahnvex** [comment]
@euwest

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by euwest** [comment]
it should totally be `browserifi18n`

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by kahnvex** [comment]
> it should totally be browserifi18n

Funny, but no.

**Comment by euwest** [comment]
:+1:

**Comment by beck** [comment]
another suggestion, if we wanted to keep this repo just for handlebars: `browserify-i18n-hbs`

**Comment by kahnvex** [comment]
> if we wanted to keep this repo just for handlebars

I don't think we want to do that. This should work for any template or html code.

**Pull request merged**
